In [1]:
import pandas as pd
import sqlalchemy as sa
import pymysql
from pathlib import Path

In [2]:
url = "mysql+pymysql://kenshu:kenshu@10.110.55.59:3306/kenshu?charset=utf8"
engine = sa.create_engine(url)
con = engine.connect()

path = r"\\10.110.0.44\everyone\test_01"

folder = Path(path)
csv_files = list(folder.glob("*.csv"))
csv_files

[WindowsPath('//10.110.0.44/everyone/test_01/2101_検査結果.csv'),
 WindowsPath('//10.110.0.44/everyone/test_01/2102_検査結果.csv'),
 WindowsPath('//10.110.0.44/everyone/test_01/2103_検査結果.csv')]

In [3]:
df_e = pd.read_excel(r"\\10.110.0.44\everyone\test_01/Destination_Master.xlsx", skiprows=2) 
df_e = df_e[['D_CODE', 'D_NAME']]
df_e

  D_CODE D_NAME
0      A   谷川化学
1      B   三木食品
2      C   福間物産
3      D   後藤建設

In [4]:
df_all = pd.DataFrame()
list_d = []

for csv_file in csv_files:
    df = pd.read_csv(csv_file, encoding='cp932')
    df = df.fillna(0)
    df['不良数'] = df['不良1'] + df['不良2'] + df['不良3']
    list_d.append(df)
#     display(df)

df_all = pd.concat(list_d)
df_all = df_all.sort_values(['LOTNO'])
df_all

   LOTNO  不良1  不良2  不良3 D_CODE  不良数
0   a050  1.0  0.0  0.0      A  1.0
1   a049  0.0  0.0  0.0      D  0.0
2   a048  0.0  1.0  0.0      D  1.0
3   a047  0.0  0.0  1.0      C  1.0
4   a046  0.0  0.0  0.0      D  0.0
5   a045  0.0  0.0  0.0      A  0.0
6   a044  1.0  0.0  1.0      B  2.0
7   a043  5.0  0.0  0.0      A  5.0
8   a042  6.0  0.0  1.0      A  7.0
9   a041  3.0  0.0  0.0      B  3.0
10  a040  0.0  0.0  0.0      C  0.0
11  a039  0.0  0.0  0.0      C  0.0
12  a038  0.0  4.0  0.0      D  4.0
13  a037  0.0  0.0  0.0      B  0.0
14  a036  1.0  0.0  1.0      C  2.0
15  a035  0.0  0.0  0.0      B  0.0
16  a034  0.0  5.0  0.0      B  5.0
17  a033  0.0  1.0  0.0      B  1.0
18  a032  0.0  0.0  0.0      C  0.0
19  a031  0.0  0.0  0.0      B  0.0
20  a030  0.0  0.0  0.0      B  0.0
21  a029  0.0  1.0  0.0      D  1.0
22  a028  0.0  1.0  0.0      C  1.0
23  a027  1.0  1.0  0.0      B  2.0
24  a026  0.0  0.0  0.0      C  0.0
25  a025  0.0  0.0  0.0      B  0.0
26  a024  0.0  3.0  0.0      B  3.0
27  a023  0.0  0.0  8.0      B  8.0
28  a022  1.0  0.0  0.0      B  1.0
29  a021  0.0  0.0  0.0      C  0.0
30  a020  8.0  0.0  0.0      D  8.0
31  a019  1.0  0.0  0.0      B  1.0
32  a018  0.0  0.0  0.0      B  0.0
33  a017  0.0  0.0  1.0      B  1.0
34  a016  0.0  0.0  0.0      A  0.0
35  a015  4.0  0.0  0.0      A  4.0
36  a014  0.0  0.0  0.0      B  0.0
37  a013  0.0  0.0  1.0      A  1.0
38  a012  0.0  0.0  8.0      B  8.0
39  a011  0.0  0.0  0.0      C  0.0
40  a010  0.0  1.0  0.0      C  1.0
41  a009  0.0  0.0  0.0      D  0.0
42  a008  0.0  1.0  0.0      B  1.0
43  a007  0.0  0.0  0.0      C  0.0
44  a006  0.0  0.0  0.0      D  0.0
45  a005  0.0  6.0  0.0      D  6.0
46  a004  0.0  0.0  0.0      B  0.0
47  a003  0.0  0.0  0.0      A  0.0
48  a002  1.0  0.0  0.0      B  1.0
49  a001  0.0  0.0  0.0      C  0.0

   LOTNO  不良1  不良2  不良3 D_CODE  不良数
0   a100  5.0  0.0  0.0      D  5.0
1   a099  1.0  0.0  0.0      C  1.0
2   a098  0.0  0.0  0.0      C  0.0
3   a097  0.0  4.0  0.0      A  4.0
4   a096  0.0  0.0  0.0      D  0.0
5   a095  0.0  0.0  0.0      B  0.0
6   a094  0.0  0.0  0.0      A  0.0
7   a093  1.0  0.0  0.0      A  1.0
8   a092  0.0  0.0  3.0      A  3.0
9   a091  0.0  0.0  0.0      D  0.0
10  a090  0.0  0.0  1.0      A  1.0
11  a089  0.0  0.0  0.0      C  0.0
12  a088  0.0  0.0  0.0      B  0.0
13  a087  0.0  0.0  0.0      C  0.0
14  a086  0.0  0.0  0.0      C  0.0
15  a085  0.0  0.0  0.0      D  0.0
16  a084  0.0  0.0  0.0      D  0.0
17  a083  0.0  0.0  0.0      D  0.0
18  a082  0.0  0.0  0.0      B  0.0
19  a081  1.0  0.0  0.0      D  1.0
20  a080  0.0  0.0  0.0      C  0.0
21  a079  0.0  0.0  3.0      B  3.0
22  a078  0.0  4.0  0.0      B  4.0
23  a077  0.0  0.0  0.0      B  0.0
24  a076  0.0  8.0  0.0      B  8.0
25  a075  0.0  6.0  0.0      B  6.0
26  a074  0.0  0.0  0.0      C  0.0
27  a073  0.0  0.0  0.0      B  0.0
28  a072  0.0  0.0  0.0      A  0.0
29  a071  0.0  0.0  0.0      B  0.0
30  a070  1.0  0.0  7.0      B  8.0
31  a069  0.0  0.0  0.0      B  0.0
32  a068  0.0  0.0  0.0      A  0.0
33  a067  0.0  0.0  0.0      C  0.0
34  a066  0.0  0.0  0.0      D  0.0
35  a065  0.0  0.0  0.0      D  0.0
36  a064  1.0  0.0  0.0      B  1.0
37  a063  0.0  1.0  0.0      D  1.0
38  a062  0.0  0.0  2.0      C  2.0
39  a061  0.0  0.0  0.0      B  0.0
40  a060  0.0  0.0  1.0      A  1.0
41  a059  1.0  0.0  0.0      A  1.0
42  a058  0.0  2.0  0.0      B  2.0
43  a057  0.0  0.0  0.0      C  0.0
44  a056  0.0  0.0  0.0      C  0.0
45  a055  0.0  0.0  0.0      D  0.0
46  a054  0.0  0.0  0.0      C  0.0
47  a053  0.0  5.0  0.0      C  5.0
48  a052  0.0  0.0  3.0      B  3.0
49  a051  0.0  0.0  0.0      A  0.0

   LOTNO  不良1  不良2  不良3 D_CODE   不良数
0   a130  0.0  2.0  0.0      A   2.0
1   a129  0.0  0.0  0.0      D   0.0
2   a128  0.0  0.0  0.0      A   0.0
3   a127  0.0  0.0  0.0      D   0.0
4   a126  0.0  1.0  0.0      D   1.0
5   a125  0.0  1.0  0.0      C   1.0
6   a124  0.0  0.0  0.0      B   0.0
7   a123  0.0  2.0  0.0      D   2.0
8   a122  0.0  0.0  0.0      D   0.0
9   a121  0.0  1.0  0.0      D   1.0
10  a120  0.0  0.0  0.0      A   0.0
11  a119  0.0  0.0  0.0      D   0.0
12  a118  0.0  0.0  0.0      A   0.0
13  a117  6.0  0.0  0.0      C   6.0
14  a116  0.0  0.0  5.0      C   5.0
15  a115  0.0  0.0  0.0      C   0.0
16  a114  0.0  0.0  4.0      A   4.0
17  a113  0.0  4.0  0.0      D   4.0
18  a112  0.0  0.0  0.0      A   0.0
19  a111  0.0  0.0  0.0      C   0.0
20  a110  0.0  0.0  0.0      C   0.0
21  a109  0.0  4.0  0.0      A   4.0
22  a108  0.0  0.0  0.0      A   0.0
23  a107  0.0  0.0  0.0      B   0.0
24  a106  0.0  7.0  0.0      A   7.0
25  a105  1.0  9.0  0.0      A  10.0
26  a104  0.0  0.0  0.0      A   0.0
27  a103  0.0  0.0  8.0      A   8.0
28  a102  0.0  0.0  0.0      C   0.0
29  a101  0.0  0.0  0.0      D   0.0

   LOTNO  不良1  不良2  不良3 D_CODE  不良数
49  a001  0.0  0.0  0.0      C  0.0
48  a002  1.0  0.0  0.0      B  1.0
47  a003  0.0  0.0  0.0      A  0.0
46  a004  0.0  0.0  0.0      B  0.0
45  a005  0.0  6.0  0.0      D  6.0
..   ...  ...  ...  ...    ...  ...
4   a126  0.0  1.0  0.0      D  1.0
3   a127  0.0  0.0  0.0      D  0.0
2   a128  0.0  0.0  0.0      A  0.0
1   a129  0.0  0.0  0.0      D  0.0
0   a130  0.0  2.0  0.0      A  2.0

[130 rows x 6 columns]

In [5]:
df_f = df_all.merge(df_e, how='left', on=['D_CODE'])
df_f = df_f[['LOTNO', 'D_CODE', 'D_NAME', '不良数', '不良1', '不良2', '不良3']]
df_f

    LOTNO D_CODE D_NAME  不良数  不良1  不良2  不良3
0    a001      C   福間物産  0.0  0.0  0.0  0.0
1    a002      B   三木食品  1.0  1.0  0.0  0.0
2    a003      A   谷川化学  0.0  0.0  0.0  0.0
3    a004      B   三木食品  0.0  0.0  0.0  0.0
4    a005      D   後藤建設  6.0  0.0  6.0  0.0
..    ...    ...    ...  ...  ...  ...  ...
125  a126      D   後藤建設  1.0  0.0  1.0  0.0
126  a127      D   後藤建設  0.0  0.0  0.0  0.0
127  a128      A   谷川化学  0.0  0.0  0.0  0.0
128  a129      D   後藤建設  0.0  0.0  0.0  0.0
129  a130      A   谷川化学  2.0  0.0  2.0  0.0

[130 rows x 7 columns]

In [6]:
df_f.columns

Index(['LOTNO', 'D_CODE', 'D_NAME', '不良数', '不良1', '不良2', '不良3'], dtype='object')

In [7]:
table = "fuku_kenshu06"
df_f.to_sql(f"{table}", engine, if_exists="replace", index=None)

```SQL
alter table kenshu.fuku_kenshu06
modify LOTNO varchar (4), 
modify D_CODE varchar (1), 
modify D_NAME varchar (10), 
modify 不良数 int, 
modify 不良1 int, 
modify 不良2 int, 
modify 不良3 int, 
add primary key (LOTNO)
```