In [1]:
# データ加工
import numpy as np
import pandas as pd

# 可視化
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib import rcParams 
plt.rcParams["font.family"] = "MS Gothic"
from matplotlib import colors
import matplotlib.dates as mdates
import seaborn as sns

# その他
import datetime
import openpyxl
import warnings
import os
import glob
import fitz

# 手入力

In [13]:
"""
変数の定義
"""

#input path
eqdata_Path = r'C:\Users\00220401626\Desktop\2217034-000\2217034-000'
Timedata_Path = r'C:\Users\00220401626\Desktop\General\05_グライディングセンタ\05_グライディングセンタ\time_data\*.csv'

#output Path
output_dir = r"C:\Users\00220401626\Desktop\2217034-000\\"

# eq_data加工

In [3]:
"""
eq_data : As-prerared eq_data
"""
eqPath = []

for root, dirs, files in os.walk(eqdata_Path):
    for f in files:
        # 指定したフォルダ内のファイル情報をすべて取得
        full = os.path.join(root, f)
        eqPath.append(full)
        # print(eqPath)
print('全ファイルパス取得完了')
print('現在、全eq_detaを縦結合しています。')

eq_data = pd.DataFrame()
for p in eqPath:    
    t = os.path.getmtime(p)
    D = datetime.datetime.fromtimestamp(t).strftime('%Y/%m/%d %H:%M:%S.%f')[:-3]#最終更新日時をタイムスタンプ型に変換
    
    # ファイル読み込み、整形
    d = pd.read_csv(p, skiprows=2,encoding="cp932")
    d = d.rename(columns={'Time': 'Time(msec)', 'POSF': 'POSF(mm)','POSF.1': 'POSF.1(mm)','TCMD':'TCMD(%)','TCMD.1':'TCMD.1(%)','TCMD.2':'TCMD.2(%)','TCMD.3':'TCMD.3(%)','TCMD.4':'TCMD.4(%)','SPEED':'SPEED(1/min)'})
    d = d.dropna()
    
    d["latest_time"] = D
    d["latest_time"] = pd.to_datetime(d["latest_time"])#最終更新日時をdatetime型に変換
    d['Time(msec)'] = (d['Time(msec)'].astype(float).astype(int))/1000 # d['Time(msec)'] = d['Time(msec)']/1000
    d['lt_unix'] = d.latest_time.apply(lambda t: int(t.timestamp()))
    d['lt_unix3'] = ((d['lt_unix'] - 299.995) + d['Time(msec)']).astype(int)# d['lt_unix2'] = (d['lt_unix']-299.995)
    d['lt'] = pd.to_datetime(d['lt_unix3'], unit='s')
    eq_data = pd.concat([eq_data,d], axis=0, ignore_index=True)
        
eq_data = eq_data[['lt','Time(msec)','POSF(mm)','POSF.1(mm)','TCMD(%)','TCMD.1(%)','TCMD.2(%)','TCMD.3(%)','TCMD.4(%)','SPEED(1/min)']]
print(eq_data.shape)
eq_data.head()

全ファイルパス取得完了
現在、全eq_detaを縦結合しています。
(18120000, 10)

,lt,Time(msec),POSF(mm),POSF.1(mm),TCMD(%),TCMD.1(%),TCMD.2(%),TCMD.3(%),TCMD.4(%),SPEED(1/min)
0,2022-11-21 18:02:02,0.000,-75421.330000000002000,-1668.866950000000100,0.178522383960450,0.370777258994782,1.057401812688822,-7.209557813787421,4.976806640625000,3500.199999999999800
1,2022-11-21 18:02:02,0.005,-75421.324000000008000,-1668.875350000000000,0.192254875034331,0.851414446580610,0.961274375171656,-8.637736885471025,5.605468750000000,3499.200000000000300
2,2022-11-21 18:02:02,0.010,-75421.337000000000000,-1668.883650000000000,0.521834660807470,0.755287009063444,0.878879428728371,-8.129634715737435,5.350341796875000,3498.199999999999800
3,2022-11-21 18:02:02,0.015,-75421.338000000003000,-1668.891850000000000,0.466904696511947,-0.205987366108212,0.988739357319418,-7.031035429826971,5.313720703125000,3498.800000000000200
4,2022-11-21 18:02:02,0.020,-75421.328000000009000,-1668.900050000000200,0.151057401812689,0.659159571546278,0.933809393023895,-8.198297171106839,5.250244140625000,3498.199999999999800

In [4]:
"""
eq : データ加工後のeq_data
"""
eq = eq_data

#カラムの要素の変更
for col in eq.columns[1:]:
    eq[col] = eq[col].astype(float)
print(eq.info())

#カラム名を変更
eq = eq.rename(columns={'TCMD(%)': 'X軸_TCMD(%)', 'TCMD.1(%)': 'Z軸_TCMD(%)','TCMD.2(%)':'B軸_TCMD(%)','TCMD.3(%)':'C軸_TCMD(%)','TCMD.4(%)':'スピンドル_TCMD(%)'})

#カラムの削除
eq = eq.drop(['Time(msec)','POSF(mm)','POSF.1(mm)'],axis=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18120000 entries, 0 to 18119999
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   lt            datetime64[ns]
 1   Time(msec)    float64
 2   POSF(mm)      float64
 3   POSF.1(mm)    float64
 4   TCMD(%)       float64
 5   TCMD.1(%)     float64
 6   TCMD.2(%)     float64
 7   TCMD.3(%)     float64
 8   TCMD.4(%)     float64
 9   SPEED(1/min)  float64
dtypes: datetime64[ns](1), float64(9)
memory usage: 1.4 GB
None

### 秋山ver

In [6]:
"""
eq_selected : ステップ60で絞ったeq_data (加工開始時間と終了時間を抽出する際に使用する）

"""
# 一定間隔で取り出して1製品分の加工時間を抽出
step = 60
eq_selected = eq.loc[::step].reset_index(drop=True)
eq_selected = eq_selected.sort_values('lt').reset_index(drop=True)#時系列ごとになってなかったので並び替え


# 時系列順にしてから平均を取る。fh_s→前半の約６分のSPEED平均　sh_s→後半の約１分のSPEED平均
for index, row in eq_selected.iterrows(): 
    start = index
    end = start + 1300
    eq_selected.loc[index, 'fh_s'] = eq_selected.loc[start:end, 'SPEED(1/min)'].mean()
    
for index, row in eq_selected.iterrows(): 
    start = index + 1500
    end = start + 400
    eq_selected.loc[index, 'sh_s'] = eq_selected.loc[start:end, 'SPEED(1/min)'].mean()

In [7]:
eq_selected.fillna(0, inplace=True)
eq_selected

,lt,X軸_TCMD(%),Z軸_TCMD(%),B軸_TCMD(%),C軸_TCMD(%),スピンドル_TCMD(%),SPEED(1/min),fh_s,sh_s
0,2022-11-18 06:57:54,1.002472,-1.441912,-0.988739,-1.853886,0.0,0.2,2113.474712,3469.217456
1,2022-11-18 06:57:54,0.933809,-1.441912,-0.988739,-1.840154,0.0,0.0,2116.163874,3460.494264
2,2022-11-18 06:57:54,0.810217,-1.441912,-0.961274,-1.840154,0.0,-0.8,2118.854266,3451.769576
3,2022-11-18 06:57:54,0.700357,-1.332052,-0.988739,-1.798956,0.0,0.0,2121.544504,3443.044888
4,2022-11-18 06:57:55,0.796484,-1.551771,-0.961274,-1.812689,0.0,-0.8,2124.233051,3434.318703
...,...,...,...,...,...,...,...,...,...
301995,2022-11-21 19:02:16,0.357045,-1.661631,-0.343312,-1.771491,0.0,-0.2,-0.120000,0.000000
301996,2022-11-21 19:02:16,0.398242,-1.744026,-0.315847,-1.744026,0.0,0.0,-0.100000,0.000000
301997,2022-11-21 19:02:17,0.535567,-1.853886,-0.343312,-1.744026,0.0,-0.2,-0.133333,0.000000
301998,2022-11-21 19:02:17,0.494370,-1.840154,-0.343312,-1.785224,0.0,0.0,-0.100000,0.000000
301999,2022-11-21 19:02:17,0.109860,-1.826421,-0.315847,-1.757759,0.0,-0.2,-0.200000,0.000000

In [8]:
eqtime_list_s =[]
eqtime_list_g =[]
for time,speed,speed2,fh_ave,sh_ave,Ctcmd in zip(eq_selected['lt'], eq_selected['SPEED(1/min)'],eq_selected['SPEED(1/min)'].iloc[3:],eq_selected['fh_s'],eq_selected['sh_s'],eq_selected['C軸_TCMD(%)'].iloc[1000:]):
    if (speed > 10.0) & (speed <= 2500.0) & (speed2 >= 3000.0) & (fh_ave > 3300.0) & (Ctcmd < 0):
        eqtime_list_s.append(time)#加工開始
        if sh_ave >= 3000.0:
            eqtime_list_g.append(time + datetime.timedelta(minutes=9,seconds=55))#910加工終了
        elif sh_ave < 3000.0:
            eqtime_list_g.append(time + datetime.timedelta(minutes=6,seconds=58))#1214加工終了

print('1製品毎の加工時間を抽出完了')
# print(time_list_s)

#抽出した加工時間をデータフレーム化
eqtime_list_s2 = []
eqtime_list_g2 = []
eqtime_list = []
for s in eqtime_list_s:
    for g in eqtime_list_g:
        t = g - s
        if (s not in eqtime_list_s2) & (g not in eqtime_list_g2):
            eqtime_list_s2.append(s)
            eqtime_list_g2.append(g)
            eqtime_list.append(t)
eq_s = pd.DataFrame(eqtime_list_s2, columns = ['加工開始時間'])
eq_g = pd.DataFrame(eqtime_list_g2, columns = ['加工終了時間'])
eq_t = pd.DataFrame(eqtime_list, columns = ['経過時間'])
eq_processing_time = pd.concat([eq_s, eq_g, eq_t], axis=1)

pd.set_option('display.max_rows', None)#作成したデータフレーム結果をすべて表示する#以降すべてに反映されるので注意！
pd.set_option('display.max_columns', None)#作成したデータフレーム結果をすべて表示する#以降すべてに反映されるので注意！
eq_processing_time

1製品毎の加工時間を抽出完了

                加工開始時間              加工終了時間            経過時間
0  2022-11-18 07:00:28 2022-11-18 07:07:26 0 days 00:06:58
1  2022-11-18 07:13:48 2022-11-18 07:20:46 0 days 00:06:58
2  2022-11-18 07:13:49 2022-11-18 07:20:47 0 days 00:06:58
3  2022-11-18 07:25:34 2022-11-18 07:32:32 0 days 00:06:58
4  2022-11-18 07:25:35 2022-11-18 07:32:33 0 days 00:06:58
5  2022-11-18 07:43:58 2022-11-18 07:50:56 0 days 00:06:58
6  2022-11-18 07:43:59 2022-11-18 07:50:57 0 days 00:06:58
7  2022-11-18 07:59:17 2022-11-18 08:06:15 0 days 00:06:58
8  2022-11-18 08:14:12 2022-11-18 08:21:10 0 days 00:06:58
9  2022-11-18 08:14:13 2022-11-18 08:21:11 0 days 00:06:58
10 2022-11-18 08:34:24 2022-11-18 08:41:22 0 days 00:06:58
11 2022-11-18 08:49:06 2022-11-18 08:56:04 0 days 00:06:58
12 2022-11-18 08:49:07 2022-11-18 08:56:05 0 days 00:06:58
13 2022-11-18 09:08:54 2022-11-18 09:15:52 0 days 00:06:58
14 2022-11-18 09:22:59 2022-11-18 09:29:57 0 days 00:06:58
15 2022-11-18 09:41:52 2022-11-18 09:48:50 0 days 00:06:58
16 2022-11-18 10:07:21 2022-11-18 10:14:19 0 days 00:06:58
17 2022-11-18 10:25:45 2022-11-18 10:32:43 0 days 00:06:58
18 2022-11-18 10:25:46 2022-11-18 10:32:44 0 days 00:06:58
19 2022-11-18 12:05:34 2022-11-18 12:12:32 0 days 00:06:58
20 2022-11-18 12:42:53 2022-11-18 12:49:51 0 days 00:06:58
21 2022-11-18 12:42:54 2022-11-18 12:49:52 0 days 00:06:58
22 2022-11-18 12:53:52 2022-11-18 13:00:50 0 days 00:06:58
23 2022-11-18 13:07:07 2022-11-18 13:14:05 0 days 00:06:58
24 2022-11-18 13:18:07 2022-11-18 13:25:05 0 days 00:06:58
25 2022-11-18 13:37:03 2022-11-18 13:44:01 0 days 00:06:58
26 2022-11-18 13:53:46 2022-11-18 14:00:44 0 days 00:06:58
27 2022-11-18 15:24:10 2022-11-18 15:31:08 0 days 00:06:58
28 2022-11-18 15:24:11 2022-11-18 15:31:09 0 days 00:06:58
29 2022-11-18 15:39:45 2022-11-18 15:46:43 0 days 00:06:58
30 2022-11-18 15:53:41 2022-11-18 16:00:39 0 days 00:06:58
31 2022-11-18 15:53:42 2022-11-18 16:00:40 0 days 00:06:58
32 2022-11-18 16:08:00 2022-11-18 16:14:58 0 days 00:06:58
33 2022-11-18 16:24:52 2022-11-18 16:31:50 0 days 00:06:58
34 2022-11-18 16:41:24 2022-11-18 16:48:22 0 days 00:06:58
35 2022-11-18 16:56:00 2022-11-18 17:02:58 0 days 00:06:58
36 2022-11-18 17:10:46 2022-11-18 17:17:44 0 days 00:06:58
37 2022-11-18 17:28:48 2022-11-18 17:35:46 0 days 00:06:58
38 2022-11-18 17:28:49 2022-11-18 17:35:47 0 days 00:06:58
39 2022-11-18 17:43:42 2022-11-18 17:50:40 0 days 00:06:58
40 2022-11-18 17:43:43 2022-11-18 17:50:41 0 days 00:06:58
41 2022-11-18 17:57:38 2022-11-18 18:04:36 0 days 00:06:58
42 2022-11-18 17:57:39 2022-11-18 18:04:37 0 days 00:06:58
43 2022-11-18 18:11:24 2022-11-18 18:18:22 0 days 00:06:58
44 2022-11-18 18:25:26 2022-11-18 18:32:24 0 days 00:06:58
45 2022-11-18 18:39:54 2022-11-18 18:46:52 0 days 00:06:58
46 2022-11-18 18:39:55 2022-11-18 18:46:53 0 days 00:06:58
47 2022-11-18 20:12:47 2022-11-18 20:19:45 0 days 00:06:58
48 2022-11-18 20:27:06 2022-11-18 20:34:04 0 days 00:06:58
49 2022-11-18 20:51:13 2022-11-18 20:58:11 0 days 00:06:58
50 2022-11-18 20:51:14 2022-11-18 20:58:12 0 days 00:06:58
51 2022-11-18 21:06:39 2022-11-18 21:13:37 0 days 00:06:58
52 2022-11-18 21:06:40 2022-11-18 21:13:38 0 days 00:06:58
53 2022-11-18 21:20:35 2022-11-18 21:27:33 0 days 00:06:58
54 2022-11-18 21:20:36 2022-11-18 21:27:34 0 days 00:06:58
55 2022-11-18 21:34:53 2022-11-18 21:41:51 0 days 00:06:58
56 2022-11-18 21:34:54 2022-11-18 21:41:52 0 days 00:06:58
57 2022-11-18 21:49:14 2022-11-18 21:56:12 0 days 00:06:58
58 2022-11-18 22:07:26 2022-11-18 22:14:24 0 days 00:06:58
59 2022-11-18 22:21:14 2022-11-18 22:28:12 0 days 00:06:58
60 2022-11-21 09:28:47 2022-11-21 09:35:45 0 days 00:06:58
61 2022-11-21 09:28:48 2022-11-21 09:35:46 0 days 00:06:58
62 2022-11-21 09:42:23 2022-11-21 09:49:21 0 days 00:06:58
63 2022-11-21 09:42:24 2022-11-21 09:49:22 0 days 00:06:58
64 2022-11-21 09:58:28 2022-11-21 10:05:26 0 days 00:06:58
65 2022-11-21 09:58:29 2022-11-21 10:05:27 0 days 00:06:58
66 2022-11-21 10:14:17 2022-11-21 10:21:15 0 days 00:06:58
67 2022-11-21 10:28:12 2022-11-21 10:35:10 0 days 00:06:58
68 2022-11-21 10:42:39 2022-11-21 10:49:37 0 days 00:06:58
69 2022-11-21 12:16:35 2022-11-21 12:23:33 0 days 00:06:58
70 2022-11-21 12:30:41 2022-11-21 12:37:39 0 days 00:06:58
71 2022-11-21 12:57:00 2022-11-21 13:03:58 0 days 00:06:58
72 2022-11-21 12:57:01 2022-11-21 13:03:59 0 days 00:06:58
73 2022-11-21 13:12:49 2022-11-21 13:19:47 0 days 00:06:58
74 2022-11-21 13:12:50 2022-11-21 13:19:48 0 days 00:06:58
75 2022-11-21 13:46:29 2022-11-21 13:53:27 0 days 00:06:58
76 2022-11-21 13:46:30 2022-11-21 13:53:28 0 days 00:06:58
77 2022-11-21 13:57:48 2022-11-21 14:04:46 0 days 00:06:58
78 2022-11-21 14:13:00 2022-11-21 14:19:58 0 days 00:06:58
79 2022-11-21 14:13:01 2022-11-21 14:19:59 0 days 00:06:58
80 2022-11-21 14:29:20 2022-11-21 14:36:18 0 days 00:06:58
81 2022-11-21 14:50:24 2022-11-21 14:57:22 0 days 00:06:58
82 2022-11-21 15:12:54 2022-11-21 15:19:52 0 days 00:06:58
83 2022-11-21 15:29:15 2022-11-21 15:36:13 0 days 00:06:58
84 2022-11-21 15:45:59 2022-11-21 15:52:57 0 days 00:06:58
85 2022-11-21 15:46:00 2022-11-21 15:52:58 0 days 00:06:58
86 2022-11-21 16:01:24 2022-11-21 16:08:22 0 days 00:06:58
87 2022-11-21 16:30:13 2022-11-21 16:37:11 0 days 00:06:58
88 2022-11-21 16:44:57 2022-11-21 16:51:55 0 days 00:06:58
89 2022-11-21 16:44:58 2022-11-21 16:51:56 0 days 00:06:58
90 2022-11-21 17:05:34 2022-11-21 17:12:32 0 days 00:06:58
91 2022-11-21 17:05:35 2022-11-21 17:12:33 0 days 00:06:58
92 2022-11-21 17:19:31 2022-11-21 17:26:29 0 days 00:06:58
93 2022-11-21 17:19:32 2022-11-21 17:26:30 0 days 00:06:58
94 2022-11-21 18:21:59 2022-11-21 18:28:57 0 days 00:06:58
95 2022-11-21 18:22:00 2022-11-21 18:28:58 0 days 00:06:58
96 2022-11-21 18:38:47 2022-11-21 18:45:45 0 days 00:06:58

# time_data加工

In [9]:
"""
time_data: As-prepared time data
"""
#time_data加工
files2 = glob.glob(Timedata_Path)
df_list = [ pd.read_csv(file,encoding="cp932") for file in files2]
time_data = pd.concat(df_list, axis = 0, ignore_index=True)
print(time_data.shape)
time_data.head()

(590, 4)

         LotNo  FLAG                 開始時間                 終了時間
0  0000000-000     1  2022-11-08 14:31:00  2022-11-08 14:39:00
1  0000000-000     2  2022-11-08 14:49:00  2022-11-08 14:56:00
2  0000000-000     2  2022-11-08 15:00:00  2022-11-08 15:07:00
3  2216584-000     0  2022-11-08 15:13:00  2022-11-08 15:20:00
4  2216584-000     0  2022-11-08 15:27:00  2022-11-08 15:35:00

In [10]:
### LOT情報取り出し
LOT_LIST = time_data['LotNo'].unique()
LOT_LIST = LOT_LIST.tolist()
AZUL910 = ['0000000-000','2217179-000','2218571-000','2217682-000']
AZUL1214 = ['0000000-000','2216584-000','2217395-000','2215700-000','2216857-000','2217343-000','2217034-000']

#### 1214
LOT_LIST_1214 = [i for i in LOT_LIST if i not in AZUL910]
LOT_LIST_1214

#### 910
# LOT_LIST_910 = [i for i in LOT_LIST if i not in AZUL1214]
# LOT_LIST_910

['2216584-000',
 '2217395-000',
 '2215700-000',
 '2216857-000',
 '2217343-000',
 '2217034-000']

In [11]:
"""
td : データクレンジング後のtimedata
td_0 : tdをフラグ0で絞り込み
td_12 : tdをフラグ1 & 2で絞り込み
"""
td = time_data
# 時間をdatatime型に変換
td["開始時間"] = pd.to_datetime(td["開始時間"])
td["終了時間"] = pd.to_datetime(td["終了時間"])
#クレンジング
td = td.loc[(td["FLAG"] == 0)|(td["FLAG"] == 1)|(td["FLAG"] == 2)]
td.head()

         LotNo  FLAG                開始時間                終了時間
0  0000000-000     1 2022-11-08 14:31:00 2022-11-08 14:39:00
1  0000000-000     2 2022-11-08 14:49:00 2022-11-08 14:56:00
2  0000000-000     2 2022-11-08 15:00:00 2022-11-08 15:07:00
3  2216584-000     0 2022-11-08 15:13:00 2022-11-08 15:20:00
4  2216584-000     0 2022-11-08 15:27:00 2022-11-08 15:35:00

# eq_dataとtimedataの結合

In [14]:
for LOT in LOT_LIST_1214:    
    #FLAGで絞り込み
    td_0 = td.loc[(td["FLAG"] == 0) & (td["LotNo"] == LOT)]
    #期間を設定
    START = td_0.iloc[0]["開始時間"]
    FINISH = td_0.iloc[-1]["終了時間"]
    print(LOT)
    print(START)
    print(FINISH)
    
    # td_0 = td_0.loc[(td_0['開始時間'] >= START) & (td_0['開始時間'] <= FINISH)]
    td_12 = td.loc[(td["FLAG"] == 1)|(td["FLAG"] == 2)]
    td_12 = td_12.loc[(td_12['開始時間'] >= START) & (td_12['開始時間'] <= FINISH)]
    # print(td_0.info())
   

    """
    df_time_start : timedataの加工開始時間
    df_eq_start : eqdataの加工開始時間
    df_comb_start : timedataの加工開始時間とeqdataの加工開始時間の結合したデータフレーム
    """
    time_start = []
    eq_start = []

    for a in td_0['開始時間']:
        for b in eq_processing_time['加工開始時間']:
            if (b < ( a + datetime.timedelta(minutes= 10 ))) and (b > ( a + datetime.timedelta(minutes= -10 ))):
                if (a not in time_start) & (b not in eq_start):
                    time_start.append(a)
                    eq_start.append(b)
            continue


    df_time_start = pd.DataFrame(time_start, columns = ['開始時間'])
    df_eq_start = pd.DataFrame(eq_start, columns = ['加工開始時間'])
    df_comb_start = pd.concat([df_time_start, df_eq_start], axis=1)
    print(df_comb_start.head())
    df_comb_start
    
    
    """
    df_comb : timedataとeqdataを結合したデータフレーム
    """
    df_comb = pd.merge(df_comb_start, td_0, how = "outer", on = ["開始時間"])
    # print(df_comb)
    df_comb["加工開始時間"] = pd.to_datetime(df_comb["加工開始時間"])
    # print(df_comb)
    df_comb = pd.merge(df_comb, eq_processing_time, how = "left", on = ["加工開始時間"])
    # print(df_comb)
    df_comb = pd.concat([df_comb,td_12], axis=0, ignore_index=True)

    df_comb = df_comb.rename(columns={'開始時間': 'time_加工開始時間', '加工開始時間': 'eq_加工開始時間','終了時間': 'time_加工終了時間','加工終了時間':'eq_加工終了時間'})
    df_comb = df_comb[['LotNo','FLAG','time_加工開始時間', 'time_加工終了時間','eq_加工開始時間','eq_加工終了時間','経過時間']]
    df_comb = df_comb.sort_values(['time_加工開始時間']).reset_index(drop=True)

    # print(df_comb.shape)
    
    
    #excel出力
    df_comb.to_csv(output_dir + LOT + ".csv",index=False,encoding="cp932")

2216584-000
2022-11-08 15:13:00
2022-11-08 21:54:00
Empty DataFrame
Columns: [開始時間, 加工開始時間]
Index: []
2217395-000
2022-11-10 09:48:00
2022-11-11 14:59:00
Empty DataFrame
Columns: [開始時間, 加工開始時間]
Index: []
2215700-000
2022-11-14 12:19:00
2022-11-14 14:48:00
Empty DataFrame
Columns: [開始時間, 加工開始時間]
Index: []
2216857-000
2022-11-14 16:07:00
2022-11-16 14:56:00
Empty DataFrame
Columns: [開始時間, 加工開始時間]
Index: []
2217343-000
2022-11-16 15:34:00
2022-11-17 12:16:00
Empty DataFrame
Columns: [開始時間, 加工開始時間]
Index: []
2217034-000
2022-11-17 13:20:00
2022-11-21 18:51:00
                 開始時間              加工開始時間
0 2022-11-18 07:31:00 2022-11-18 07:25:34
1 2022-11-18 07:49:00 2022-11-18 07:43:58
2 2022-11-18 08:04:00 2022-11-18 07:59:17
3 2022-11-18 08:19:00 2022-11-18 08:14:12
4 2022-11-18 08:39:00 2022-11-18 08:34:24

# excel出力

In [16]:
"""
df_output : CSV出力するデータフレーム
"""

##時間抽出してリストに
df_comb["file"]= df_comb['eq_加工開始時間'].dt.strftime('%Y%m%d_%H%M')
filename = df_comb["file"].dropna()
filename = filename.to_numpy().tolist()
filename


i=1
for a,b in zip(df_comb['eq_加工開始時間'],df_comb['eq_加工終了時間']):
    df_output = eq.loc[(eq['lt'] >= a) & (eq['lt'] <= b)] 
    if df_output.empty:
        pass
    else:
        out_file = output_dir + filename[i-1] +" "+ LOT + '-' + str(i).zfill(3) + ".csv"
        df_output.to_csv(out_file, index=False,encoding="cp932")
        i+=1

# グラフ化

#リスト化
s2 = eq_processing_time['加工開始時間'].tolist()
g2 = eq_processing_time['加工終了時間'].tolist()
# a = eq.drop(['lt'],axis=1)
a = eq[['SPEED(1/min)']]


i = 1
# # x軸の範囲設定
for st,gt in zip(s2,g2):
    xmin = st + datetime.timedelta(seconds=-1)
    xmax = gt + datetime.timedelta(seconds= 1)
    print(xmin,xmax)
  # #グラフ作成
    for yy in a:
        df_graph = a
        plt.scatter(x = eq['lt'], y = df_graph[yy],s=25)
        plt.xlim([xmin,xmax])
        # plt.ylim([-10,10])
        plt.gcf().autofmt_xdate(rotation=30)
        myFmt = mdates.DateFormatter("%Y-%m-%d\n%H:%M:%S")
        plt.gca().xaxis.set_major_formatter(myFmt)
        # plt.xticks( np.arange(xmin,xmax,))
        # plt.title(lot + 'の推移')
        plt.xlabel('Date')
        plt.ylabel(yy)
        
                                                            
#y軸の範囲指定
        if yy == "X軸_TCMD(%)":
            plt.ylim(-3,3)
        elif yy == "Z軸_TCMD(%)":
            plt.ylim(-5,5)
        elif yy == "B軸_TCMD(%)":
            plt.ylim(0.25,1)
        elif yy == "C軸_TCMD(%)":
            plt.ylim(-16,0)
        elif yy == "スピンドル_TCMD(%)":
            plt.ylim(2,8)
        
        os.makedirs(output_dir+'/' +LOT + '/' + str(i),exist_ok=True)
        hozon_dir = output_dir+'/' +LOT + '/' + str(i)
        
        if yy == 'SPEED(1/min)':
            plt.savefig(hozon_dir + '/'+"SPEED(1min-1).png")# プロットしたグラフをファイル.pngで保存する
            i+=1
        else:
            plt.savefig(hozon_dir + '/' + yy +".png")   # プロットしたグラフをファイル.pngで保存する

        plt.show()